---
title: "Correction"
author: "James Hollway"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Correction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Correcting data

Once a dataset is collected with `import_data()`, it needs to be corrected so that it can be connected into a database. 
qDatr contains several functions geared torwards data wrangling. 
These include, for example, the `transmutate ()` function which is between between dplyr's transmute and mutate but that returns only the mutated variables and none of the variables used in the mutations. 
Other useful functions for correcting data with qDatr are geared towards data standardising. 
These include, for example, the `entitle()` function that capitalises all words in a string to enable comparison.

```
cow <- transmutate(statename = entitle(statenme)) %>% 
transmutate(Id = stateabb) %>% 
transmutate(stdate = paste(stday, stmonth, styear, sep = ".")) %>% 
transmutate(edate = paste(endday, endmonth, endyear, sep = ".")) %>% 
transmutate(Beg = lubridate::dmy(stdate)) %>% 
transmutate(End = lubridate::dmy(edate))  
```

Once the dataset has been corrected in qDatr, the cleaned dataset can be loaded into the package using the `export_data()` function. 
The function creates a data folder to store corrected datasets, while providing a citation template and a test template. 
The citation template helps cite the source of the raw data and and describe the variables in the corrected dataset. 
The test template makes sure the corrected dataset is consistent with qDatr guidelines.

```
qDatr::export_data(cow)
```

The test template is meant to ensure consistency for the corrected dataset. 
If these tests fail, users can go back to correcting the data and, then, re-run `export_data()`.  

Corrected datasets can be connected to form a three dimensional database that resembles a data-cube. 
This can be done with the help of several functions in qDatr. 
These include, for example, the `standardise_dates()` function which creates nested vectors of dates for vague date inputs into a range of dates. 

```
qDatr::standardise_dates(cow)
```
