---
title: "qDatr"
author: "James Hollway"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{qDatr}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Getting started with qDatr

qDatr stands for quantum data for the 21st century. The objective of qDatr is to be the central package in a an ecosystem of packages aimed at collecting, connecting and correcting network data across several issue-domains of global governance. The qDatr package provides the necessary tools to collect, correct and connect data of two dimensional datasets into a three dimensional databases. qDatr also allows users to contribute to the ecosystem of packages by helping to set up data packages consistent with the ecosystem.

## Downloading and installing qDatr

The development version of the package qDatr can be downloaded from GitHub. 

```
#install.package(devtools)
devtools::install_github("globalgov/qDatr")
```

The release version of the package, once released, will be offered on the CRAN repository.  

```
install.package(qDatr)
```

## Package

qDatr has package related functions that help users set-up packages consistent with the qDatr ecosystem of packages. The function `setup_package()`, for example, establishes many of the required files and folder structures for a qDatr-consistent data package. It requires that the package name starts with a the letter q as well as that the name of at least one author is declared. 

```
qDatr::setup_package("qStates", "James Hollway")
```

## Collecting data 

For data collection and loading with qDatr, the function `import_data()` creates a data-raw folder into a project or package, copies the raw data into the folder and provides a script to facilitate data loading and data correction using qDatr. The function requires that a name for the dataset (two dimensional data sheet being imported) is declared as well as the name of the issue-domain the dataset belongs which will be used to connect two-dimensional datasets into three-dimensional databases that resembles a data cube.

```
qDatr::import_data("cow", 'states')
```

## Correcting data

Once a dataset is collected with `importa_data(), it needs to be corrected so that it can be connected into a database. qDatr contains several functions geared torwards data wrangling. These include, for example, the `transmutate ()` function which is between between dplyr's transmute and mutatea but that returns only the mutated variables and none of the variables used in the mutations. Other useful functions for correcting data with qDatr are geared towards data standardising. These include, for example, the `entitle()` function that capitalises all words in a string to enable comparison.

```
cow <- transmutate(statename = entitle(statenme)) %>% 
transmutate(Id = stateabb) %>% 
transmutate(stdate = paste(stday, stmonth, styear, sep = ".")) %>% 
transmutate(edate = paste(endday, endmonth, endyear, sep = ".")) %>% 
transmutate(Beg = lubridate::dmy(stdate)) %>% 
transmutate(End = lubridate::dmy(edate))  
```

Once the dataset has been corrected in qDatr, the cleaned dataset can be loaded into the package using the `export_data()` function. The function creates a data folder to store corrected datasets, while providing a citation template and a test template. The citation template helps cite the source of the raw data and and describe the variables in the corrected dataset. The test template makes sure the corrected dataset is consistent with qDatr guidelines.

```
qDatr::export_data(cow)
```

The test template is meant to ensure consistency for the corrected dataset. If these tests fail, users can go back to correcting the data and, then, re-run `export_data()`.  

## Connecting data

Corrected datasets can be connected to form a three dimensional database that resembles a data-cube. This can be done with the help of several functions in qDatr. These include, for example, the `standardise_dates()` function which creates nested vectors of dates for vague date inputs into a range of dates. 

```
qDatr::standardise_dates(cow)
```

## Conclusion

qDatr is intended to provide an option for collecting, correcting and connecting data so that it can be dialysed across time and space while ensuring transparency, consistency and (un)certainty. For further information on qDatr please see the other vignettes, package documentation and README. 
