---
title: "Codebook for qID generated by code_agreements() function"
output:
  pdf_document: default
---

The function creates a new column of qID based on information extracted from the treaty title column of a dataset. This allows to assign unique ID to 
treaties and should facilitate the analysis of multiple datasets and the detection of duplicates or treaties from the same family. The function works 
through different steps.

### How to read a qID
A qID is a meaningful shorthand ID created from a combination of elements extracted from the agreement title and date. The qID allows users to identify 
bilateral treaties, treaty topics, type, linkage and more. 

**Type** | **Pasting** | **Pasting**
--- | --- |--- 
Bilateral | WAT_19060521A_MEX-USA | topic_uID, type_parties
Bilateral + Protocol | WAT_18840921E3_18840921_BAD-CHE | topic_uID,type(number)_linkage_parties

A bilateral treaty that is an agreement will have the following qID: "WAT_19060521A_MEX-USA". This is a combination of the topic (WAT) and date (19060521) 
with the type(A) and the parties to agreement (MEX-USA). A bilateral treaty that is any other type than an agreement (e.g. protocol, amendments) will have 
the qID under this format: "WAT_18840921E3_BAD-CHE_18830703". The topic (WAT), the date of signature of the amendment (18840921), the type (E) which refers 
to amendment, the number of amendment (3), the parties (BAD-CHE) and finally the signature date of the "mother" treaty (18830703).

**Type** | **Pasting** | **Pasting**
--- | --- |--- 
Multilateral | SPE_20050205A | topic_uID, type
Multilateral + Protocol | OTH_19920817E2_20070817 | topic_uID,type(number)_linkage

A multilateral treaty that is an agreement will have the following qID: "SPE_20050205A" which indicates the topic (SPE), signature date of the agreement 
(20050205), and the type (A). A multilateral treaty that is not an agreement will have this qID format: "OTH_19920817E2_20070817". This represents the topic
(OTH), the signature date of the amendment (19920817), the type (E), the number of amendment (2) with the linkage number (20070817) which is the signature 
date of the "mother" treaty. 

**Type** | **Pasting** | **Pasting**
--- | --- |--- 
Known treaties | 	UNCLOS_19821210 | abbreviation_uID
Amendment of known treaties | MARPOL_19731102_19900316E | abbreviation_linkage_uID,type(number)

Famous multilateral treaties have a simplified qID with an known abbreviation instead of the topic. For example, the United Nations Convention On The Law Of
The Sea will have the following qID: "UNCLOC_19821210A" which is the known abbreviation (UNCLOS), the signature date (19821210) with the type (A). The 
protocols or amendments of the known treaties will have this qID format: "MARPOL_19890317E2_19731102". It indicates the known abbreviation (MARPOL), the signature date of this specific amendment (19890317), the type of treaty (E), its number (2) and the signature date of the "mother" treaty (19731102).

There are also several steps to how the code_agreements() function work. Each step relies on a helper function to extract certain elements that later will 
be joined together to form a qID. Each of the functions can also be used as a standalone function to generate certain types of information. For more 
information on the code_agreements functions and the helper functions, please also run `?code_agreements()`. 

### Codebook

A more detailed description of how each portion of a qID is coded. 

### Parties

The first element extracted from the title is the state that is part to the treaty. The function `code_states()` from `qStates` is used. It returns 3 digit ISO codes for states.

### Unique number (uID)

Each treaty contains a unique number in their qID which refer to the signature date. The number has therefore eight numbers that are under the YYYYMMDD format and is called uID. 

### Type

The function detects the type of treaty and assign a letter that will be included in the final ID. 

* Agreements = **A**
* Amendments = **E**
* Protocol = **P**
* Exchange of Notes = **X**
* Memorandum of Understanding = **Y**
* Strategy = **S**

For amendments or protocol, their ordering number is also extracted from the title to be included in the qID. 

### Topic

Based on a list of key terms, the topics that are mentioned in the title will appear in the qID. Some of the topics covered are:

**Example**

**Words** | **Topic**
--- | ---
Waste,disposal,pollut, toxic, hazard | WAS
species,habitat,ecosystems,biological diversity,genetic resources,biosphere,birds,locusts | SPE
air,atmos,climate,outer space,ozone,emissions | AIR
water,freshwater,river,rhine,hydro,basin,drought,ocean,shelf,Atlantic,Lake | WAT
Soil,Wetland,Desert,Erosion,Land,Archipelago | SOI
nature,environment,biodiversity,flora,plant,fruit,vegetable,seed,forest,tree,conservation,preservation | BIO
fish,salmon,herring,tuna,aquaculture,mariculture,molluscs,whaling | FIS
agricultur,food,livestock,crop,irrigation,cattle,meat,farm,cultivate | AGR
culture,scien,techno,trade,research,exploration,navigation,data,information | BOT
energy,nuclear,oil,mining,gas,hydro,power | NUC
accidents | ACC
chemicals, pesticides,toxin,Lead | CHE
climate | CLC
noise | NOI
disease,diseases | DIS
resource,resources,timber,antartic,fur,Ivory,Horn | RES

### Linkages between Agreements

Treaties from the same family can be detected by removing predictable words that are added to treaty titles (e.g. amendment, protocol, meeting) and 
identifying duplicates based on the core words used to refer to main agreement. The YYYYMMDD number assigned to the "mother" treaty is used for all the 
other treaties deriving from it as the last digits in their qID.

### Known Agreements

Some treaties already have known abbreviation. The qID of these treaties contain their abbreviation instead of the topic.

**Example**

**Know Agreements** | **Topic**
--- | ---
"United Nations Convention On The Law Of The Sea" | UNCLOS
"Convention On Biological Diversity" | CBD
"Convention On The Conservation Of Antarctic Marine Living Resources" | CCAMLR
"Convention On International Trade In Endangered Species Of Wild Fauna And Flora" | CITES
"International Convention On Civil Liability For Oil Pollution Damage" | CLC
"Antarctic Mineral Resources Convention" | CRAMRA
"Convention On The Protection And Use Of Transboundary Watercourses And International Lakes" | CECE
"Convention On Long-Range Transboundary Air Pollution" | LRTAP
"International Convention For The Prevention Of Pollution From Ships" | MARPOL
"North American Agreement On Environmental Cooperation" | NAAEC
"Constitutional Agreement Of The Latin American Organization For Fisheries Development" | OLDEPESCA
"International Convention On Oil Pollution Preparedness, Response And Cooperation" | OPRC
"Convention For The Protection Of The Marine Environment Of The North East Atlantic" | OSPAR
"Paris Agreement Under The United Nations Framework Convention On Climate Change" | PARIS
"Convention On The Prior Informed Consent Procedure For Certain Hazardous Chemicals And Pesticides In International Trade" | PIC
"Convention On Wetlands Of International Importance Especially As Waterfowl Habitat" | RAMSA
"Convention To Combat Desertification In Those Countries Experiencing Serious Drought And/Or Desertification, Particularly In Africa" | UNCCD
"United Nations Framework Convention On Climate Change" | UNFCCC
"Convention For The Protection Of The Ozone Layer" | VIENNA
