on:
  pull_request:
    branches:
      - main

name: Binary checks

jobs:

  build:
    name: Build for ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest, r: 'release', artifact_name: '*.tar.gz', asset_name: macOS}
          - {os: windows-latest, r: 'release', artifact_name: '*.zip', asset_name: winOS}
          - {os: ubuntu-20.04, r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest", artifact_name: '*.tar.gz', asset_name: linuxOS}
          # - {os: ubuntu-20.04, r: 'devel', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@master

      - uses: r-lib/actions/setup-r-dependencies@master
        with:
          extra-packages: |
            rcmdcheck
            lintr
            spelling
            covr
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true

#     - name:Document
#       run: Rscript -e 'roxygen2::roxygenise()'

      - name: Binary
        run: |
          pkgbuild::clean_dll()
          binary <- pkgbuild::build(binary = TRUE, needs_compilation = TRUE, compile_attributes = TRUE)
          dir.create("build")
          file.copy(binary, "build")
        shell: Rscript {0}

      - name: Save binary artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.config.asset_name }}
          path: build/

      - name: Calculate code coverage
        run: Rscript -e "covr::codecov()"

      - name: Lint
        run: lintr::lint_package()
        shell: Rscript {0}

      # - name: Goodpractice # check if available on CRAN again in the future
      #   run: |
      #     goodpractice::gp()
      #   shell: Rscript {0}

      - name: Spell check
        run: spelling::spell_check_package()
        shell: Rscript {0}
